import pymysql

db=pymysql.connect(host='localhost',user='root',password='asdf123!@')
cur=db.cursor()

sql='CREATE DATABASE  IF NOT EXISTS TWEET_DATA'
cur.execute(sql)
sql = 'USE  TWEET_DATA'
cur.execute(sql)
)
sql = 'CREATE TABLE IF NOT EXISTS USER(ID VARCHAR(20) PRIMARY KEY,SCREEN_NAME VARCHAR(20),PLACE VARCHAR(20),STATUS VARCHAR(20),DOB DATE)'
cur.execute(sql)

sql = 'CREATE TABLE IF NOT EXISTS TWEETS(ID VARCHAR(20),FOREIGN KEY(ID) REFERENCES USER(ID),TID VARCHAR(20) UNIQUE)'
cur.execute(sql)

sql = 'CREATE TABLE IF NOT EXISTS TWEET_INFO(TID VARCHAR(20), FOREIGN KEY(TID) REFERENCES TWEETS(TID),TEXT VARCHAR(200))'
cur.execute(sql)

sql = 'CREATE TABLE IF NOT EXISTS FOLLOWING(ID VARCHAR(20), FOREIGN KEY(ID) REFERENCES USER(ID),FID VARCHAR(20) UNIQUE)'
cur.execute(sql)

sql = 'CREATE TABLE IF NOT EXISTS FOLLOWING_INFO(FID VARCHAR(20), FOREIGN KEY(FID) REFERENCES FOLLOWING(FID),F_SCREEN_NAME VARCHAR(20),F_DOB DATE)'
cur.execute(sql)

sql = 'CREATE TABLE IF NOT EXISTS LIKE/RETWEET(ID VARCHAR FOREIGN KEY(ID) REFERENCES USER(ID), TID VARCHAR(20))'
cur.execute(sql)




