import pymysql
db=pymysql.connect(host="localhost",user='root',password='asdf123!@');
cur=db.cursor()

sql='CREATE DATABASE TWEETDATA'
cur.execute(sql)

sql='CREATE TABLE USER (ID VARCHAR(20) PRIMARY KEY,SCREEN NAME VARCHAR(20),PLACE  VARCHAR(20), STATUS VARCHAR(20),DOB DATE)'
cur.execute(sql)

sql='CREATE TABLE  TWEETS (ID VARCHAR(20) REFERENCES ID FROM USER,TID VARCHAR(20))'
cur.execute(sql)

sql='CREATE TABLE TWEET INFO (TID VARCHAR(20) REFERENCES TID FROM TWEETS,TEXT VARCHAR(200))'
cur.execute(sql)

sql='CREATE TABLE FOLLOWING( ID VARCHAR(20) REFERENCES ID FROM USER,FID VARCHAR(20))'
cur.execute(sql)

sql='CREATE TABLE FOLLOWING INFO(FID VARCHAR(20) REFERENCES FID FROM FOLLOWING, FSCREENNAME VARCHAR(20), FDOB DATE'
cur.execute(sql)

sql='CREATE TABLE LIKE/RETWEET (ID VARCHAR REFERENCES ID FROM USER, TID)'
cur.execute(sql)




